### ISSUE TITLE
yarn run build rss failure

### ISSUE THREAD

**Issue by acviana** [acviana/vercel-nextjs-blog#9]
[builds](https://vercel.com/acviana/vercel-nextjs-blog/AJc8TE72bcxGqvDmQeYYZMFGLJFk) are currently failing due to a `yarn run build` error. I can reproduce locally on node v18.17.0 (`lts/hydrogen`).

```console
❯ yarn run build
yarn run v1.22.19
$ node ./scripts/gen-rss.js && next build
/Users/alexviana/dev/vercel-nextjs-blog/scripts/gen-rss.js:29
        categories: frontmatter.data.tag.split(', '),
                                         ^

TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/alexviana/dev/vercel-nextjs-blog/scripts/gen-rss.js:29:42
    at async Promise.all (index 12)
    at async generate (/Users/alexviana/dev/vercel-nextjs-blog/scripts/gen-rss.js:15:3)

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by acviana** [comment]
After more research and attempts to fix this I think what I need to do is bring all my config files (`package.json` and `theme.config.jsx` into alignment with the Nextra examples. 

This is tricky because Nextra is now using pnpm as a package manager and using pnpm-specific syntax  such as `"nextra": "workspace:*"` in his `package.json` file. I don't think this would be fixed just by switching to pnpm either because my local blog would not have the same `workspace` configuration as the master Nextra repo.

**Comment by acviana** [comment]
Fixed
